### ISSUE TITLE
authy-client is not in the NPM registry

### ISSUE THREAD

**Issue by mjabali** [seegno/authy-client#1]
Is there any chance you can publish this package on NPM? Thanks a lot!

**Comment by ruimarinho** [comment]
I'm working on the last updates before publishing a v1.0.0. Just a few more
days I suppose.

If you could give this a try on your project, I'd be very happy to
integrate your feedback before publishing a final release.

On Wednesday, April 20, 2016, Marcelo Jabali <notifications@github.com>
wrote:

> Is there any chance you can publish this package on NPM? Thanks a lot!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/seegno/authy-client/issues/1>
>


-- 
--
Rui Marinho

**Comment by mjabali** [comment]
Thanks for the feedback Rui. I've tried the registerUser functionality and
it works great. Then, I was trying to use the createApprovalRequest for
OneTouch and for some reason the example listed on the README file fails on
the async line with a *Syntax Error: Unexpected token exception* that I'm
investigating but if you have any ideas that would be great.
Thanks.

**Comment by ruimarinho** [comment]
Are you using babel-node to use the await/async syntax? Try with the Promise-based version instead if you'd like to run the code on node 4 without transpiling.

**Comment by mjabali** [comment]
Thanks. I got it working.

**Comment by ruimarinho** [comment]
Great! I'll close this issue since I'll be publishing this to npm soon.
