### ISSUE TITLE
Signature validation requires the presence of "approval_request"

### ISSUE THREAD

**Issue by holm** [seegno/authy-client#10]
The signature validation asserts that the body contains "approval_request". I think this restriction should be lifted, so the validation can also be done when the endpoint is validated in the Authy dashboard. In the test request from Authy the "approval_request" is not present.

**Comment by ruimarinho** [comment]
I would rather not relax this assert if production data requires it. Shouldn't they send `approval_request` on their test endpoint instead? I'll email them about this.

**Comment by holm** [comment]
Thanks for the update, can understand that. It is not exactly the most logical thing to have a test different from the actual payload, unless they have plans to use the hook for other events.

**Comment by ruimarinho** [comment]
No further feedback from Authy Support received yet.

**Comment by holm** [comment]
It seems they have changed the validation to support sending `approval_request`data. So this should be good to close.

**Comment by ruimarinho** [comment]
Thanks for confirming that. Removing the label.
