### ISSUE TITLE
Logging options override cached `request` object

### ISSUE THREAD

**Issue by pedrobranco** [seegno/authy-client#12]
When defining the logging options of `request` it modifies by reference the require cached object `request`, making all the system log requests that don't want to.

**Problem:** Any application that uses `request` and uses this client will log all the requests, even we do not want to log them. See [this](https://github.com/seegno/authy-client/blob/master/src/logging/request.js).

**Comment by ruimarinho** [comment]
Indeed, this is an issue with `request-debug`, which an updated will likely require using the return value of that wrapper.

**Comment by ruimarinho** [comment]
Waiting for https://github.com/request/request-debug/pull/18 to be merged.
