### ISSUE TITLE
startPhoneVerification is_ported AssertionFailedError

### ISSUE THREAD

**Issue by tsinagra** [seegno/authy-client#33]
I'm getting a validation error when calling the startPhoneVerification method. It appears that is_ported is no longer returned from Authy. When I call this method it returns a 500 Internal Server Error. When I comment out line 798 in client.js it successful returns a 200 without any errors. 

**Curl Command**
curl 'https://api.authy.com/protected/json/phones/verification/start?api_key=xxx' \
-d via='sms' \
-d phone_number='2482895124' \
-d country_code=1
{"carrier":"Pinger","is_cellphone":false,"message":"Text message sent to +1 248-289-5124.","seconds_to_expire":140,"uuid":"52ad5c80-cb9f-0134-aec9-0a2b7b0ecd88","success":true}%

**Comment by ruimarinho** [comment]
Thank you for the report. This has been fixed by https://github.com/seegno/authy-client/commit/9688c2ee8c350b77843bd077e2795208178ebb36 and released as part of https://github.com/seegno/authy-client/releases/tag/v1.0.10. On a side note, Authy changed this in production without warning developers.
