### ISSUE TITLE
Bluebird error not being passed to callback

### ISSUE THREAD

**Issue by alokrajiv** [seegno/authy-client#37]
I am using the callback syntax for sending a one-touch request. When the mobile is not really registered, i see that bluebird is throwing an error:

`async.js:61 : fn = function () { throw arg; };`

Put, this is not being passed with err to the callback.

Is this expected behaviour or a bug?

**Comment by alokrajiv** [comment]
My apologies. I was an error from my side, there was an error from my side which overwrote the error. Closed the issue.

**Comment by ruimarinho** [comment]
No problem. Glad you found the problem @alokrajiv :)
