### ISSUE TITLE
Signature validation requires x-authy-signature-nonce to be an integer

### ISSUE THREAD

**Issue by holm** [seegno/authy-client#8]
Hi

First of thanks for a really high quality library!

In the callback verification it asserts that the x-authy-signature-nonce header is an integer. However headers are always strings, so it fails this test. Since the nonce is just concatenated to the string for HMAC, it doesn't really need to parsed to an integer, and could really be any string.

Can the validation be changed to allow both a string and an integer, so to avoid users having to parse manually, but still keep backwards compatibility?

**Comment by ruimarinho** [comment]
Thanks for your kind words! I agree with you and submitted a PR to fix this (https://github.com/seegno/authy-client/pull/11).
